april first

diff --git a/bin/copy_to b/bin/copy_to
--- a/bin/copy_to
+++ b/bin/copy_to
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash
-yadOrzen=$(which yad || which zenity)
+dlgcmd=$(command -v yad || command -v zenity)
 
-[ -z "$yadOrzen" ] && exit 1
+[ -z "$dlgcmd" ] && exit 1
 
-DestToBe=`${yadOrzen} --file-selection --directory --title="Choose your target directory"`
+dest=`${dlgcmd} --file-selection --directory --title="Choose your target directory"`
 
 if [ $? -ne 0 ]; then
-    ${yadOrzen} --error --text="Operation Aborted"
+    ${dlgcmd} --error --text="Operation Aborted"
     exit 1
 fi
 
-[ -z "$DestToBe" ] && exit 1
+[ -z "$dest" ] && exit 1
 
-TargetDir=`awk -F, '{print $1}' <<<$DestToBe`
+TargetDir=`awk -F, '{print $1}' <<<$dest`
 
 old_IFS=$IFS
 IFS=$'\n'
@@ -25,28 +25,28 @@ fi
 for FullName in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
     ShortName=${FullName##*/}
     if [[ -w $TargetDir && -e $TargetDir/$ShortName ]]; then
-        confirm=$(${yadOrzen} --question --title "File already exists" --text "Overwrite File: \n$TargetDir/$ShortName?"; echo $?)
+        confirm=$(${dlgcmd} --question --title "File already exists" --text "Overwrite File: \n$TargetDir/$ShortName?"; echo $?)
         if [[ $confirm -eq 0 ]]; then
             cp -r "${FullName}" "$TargetDir/"
             if (( $? != 0 )); then
-                ${yadOrzen} --info --text "Something went wrong $TargetDir/$ShortName" --title "Failure"
+                ${dlgcmd} --info --text "Something went wrong $TargetDir/$ShortName" --title "Failure"
             fi
         fi
     else
         if [[ -w $TargetDir && ! -e $TargetDir/$ShortName ]]; then
             cp -r "${FullName}" "$TargetDir/"
             if (( $? != 0 )); then
-                ${yadOrzen} --info --text "Something went wrong $TargetDir/$ShortName" --title "Failure"
+                ${dlgcmd} --info --text "Something went wrong $TargetDir/$ShortName" --title "Failure"
             fi
         else
             UsrOwner="$(stat --format '%U' "${TargetDir}")"
-            ${yadOrzen} --text-info --text="[$UsrOwner]:$TargetDir is not writable" --title "Failure"
+            ${dlgcmd} --text-info --text="[$UsrOwner]:$TargetDir is not writable" --title "Failure"
         fi
     fi
-done | ${yadOrzen}  --progress --auto-close --title="Copy files to $TargetDir"
+done | ${dlgcmd}  --progress --auto-close --title="Copy files to $TargetDir"
 
 if [ $? -eq 1 ]; then
-    ${yadOrzen} --error --text="Cancelled!"
+    ${dlgcmd} --error --text="Cancelled!"
     IFS=$old_IFS
     exit 1
 fi
diff --git a/bin/mycommon b/bin/mycommon
--- a/bin/mycommon
+++ b/bin/mycommon
@@ -40,6 +40,16 @@ function log() {
     fi
 }
 
+function bailout () {
+    echo "Error: $@"
+    exit 1
+}
+
+# Check required software
+function precheck () {
+    hash "$1" >/dev/null 2>&1 || bailout "Please install $1"
+}
+
 # direct it all to /dev/null
 function nullify() {
     "$@" >/dev/null 2>&1
diff --git a/bin/myedit b/bin/myedit
--- a/bin/myedit
+++ b/bin/myedit
@@ -1,26 +1,19 @@
 #!/usr/bin/env bash
-set -eu
+# This script is intended to be run as an editor helper.
 
 if [ -f "$HOME/bin/mycommon" ]; then
     . "$HOME/bin/mycommon"
 fi
 
-# This script is intended to be run as an editor helper.
+XedtApps=('subl' 'subl3' 'sublime-text' 'geany' 'xed' 'gedit' 'pluma' 'leafpad' 'atom' 'vscode')
 
 function has_editor(){
-    [ -z "$1" ] && return 1;
-    local tmp=""
-    tmp=$(command -v $1)
-    if [ -z "$tmp" ]; then
-        echo ""
-        return 1
-    fi
+    local tmp="$(command -v $1)"
     echo "$tmp"
-    return 0
+    [ -z "$tmp" ] && return 1 || return 0
 }
 
 function do_edit() {
-    local XedtApps=('subl' 'subl3' 'sublime-text' 'geany' 'xed' 'gedit' 'pluma' 'leafpad' 'atom' 'vim')
     local edt=""
     
     if is_running_X ; then
@@ -47,23 +40,7 @@ function do_edit() {
 }
 
 function do_test() {
-    local subl_present=""
-    local geany_present=""
-    local xed_present=""
-    local gedit_present=""
-    local pluma_present=""
-    local atom_present=""
-    local leaf_present=""
-    local nano_present=""
-
-    subl_present=$(has_editor "subl" || has_editor "subl3")
-    geany_present=$(has_editor "geany")
-    xed_present=$(has_editor "xed")
-    gedit_present=$(has_editor "gedit")
-    pluma_present=$(has_editor "pluma")
-    atom_present=$(has_editor "atom")
-    leaf_present=$(has_editor "leafpad")
-    nano_present=$(has_editor "nano")
+    local edt=""
     
     if [ ! -z "$1" ]; then
         log "target is $1"
@@ -77,50 +54,19 @@ function do_test() {
         log "X server down"
     fi
     
-    if [ ! -z "$subl_present" ]; then
-        log "sublime present @ $subl_present"
-    else
-        log "sublime not found"
-    fi
+    for i in "${XedtApps[@]}"; do
+        edt=$(has_editor "$i")
+        if [ -n "$edt" ]; then
+            log "$i present @ $edt"
+        else
+            log "$i not found"
+        fi
+    done
     
-    if [ ! -z "$geany_present" ]; then
-        log "geany present @ $geany_present"
-    else
-        log "geany not found"
-    fi
-    
-    if [ ! -z "$xed_present" ]; then
-        log "xed present @ $xed_present"
-    else
-        log "xed not found"
-    fi
-    
-    if [ ! -z "$gedit_present" ]; then
-        log "gedit present @ $gedit_present"
-    else
-        log "gedit not found"
-    fi
-    
-    if [ ! -z "$pluma_present" ]; then
-        log "pluma present @ $pluma_present"
-    else
-        log "pluma not found"
-    fi
-    
-    if [ ! -z "$atom_present" ]; then
-        log "atom present @ $atom_present"
-    else
-        log "atom not found"
-    fi
-    
-    if [ ! -z "$leaf_present" ]; then
-        log "leafpad present @ $leaf_present"
-    else
-        log "leafpad not found"
-    fi
-
-    if [ ! -z "$nano_present" ]; then
-        log "nano present @ $nano_present"
+    edt=$(has_editor "nano")
+   
+    if [ -n "$edt" ]; then
+        log "nano present @ $edt"
     else
         log "nano not found"
     fi
@@ -140,3 +86,5 @@ case "$cmd" in
     *)
         log "Unrecognized option: $2"
 esac
+
+unset XedtApps
diff --git a/bin/myoff b/bin/myoff
--- a/bin/myoff
+++ b/bin/myoff
@@ -10,48 +10,31 @@ cmd=${1:-off}
 
 # Return 0 if xset is found.
 function xset_ok() {
-    [ $(command -v xset) ] && return 0
-    return 1
+    [ $(command -v xset) ] && return 0 || return 1
 }
 
 #off the screen if possible.
 function do_off() {
     # Only works if X is running.
-    is_running_X
-    if [ $? -ne 0 ]; then
+    
+    if is_running_X; then
         log "X server is not running";
         return 0;
     fi
-    xset_ok
-    if [ $? -eq 0 ]; then
+    
+    if xset_ok; then
         # if "off" is given as parameter, then spawn a new thread to turn off the screen
-        sleep 1 && xset dpms force off &
+        snore 1
+        xset dpms force off &
     else
         log "xset command not found";
     fi
  }
 
 function do_test() {
-    is_running_X
-    if [ $? -eq 0 ]; then
-        log "X is running"
-    else
-        log "X server down"
-    fi
-    
-    xset_ok
-    if [ $? -eq 0 ]; then
-        log "xset command can be used";
-    else
-        log "xset command not found";
-    fi
-
-    locked "debug"
-    if [ $? -eq 0 ]; then
-        log "Screen already locked"
-    else
-        log "Screen not locked"
-    fi
+    is_running_X && log "X is running" || log "X server down";
+    xset_ok && log "xset command can be used" || log "xset command not found";
+    locked "debug" && log "Screen already locked" || log "Screen not locked";
 }
 
 case "$cmd" in
