bashtop and others

diff --git a/bin/cryptIt b/bin/cryptIt
--- a/bin/cryptIt
+++ b/bin/cryptIt
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
 
+if [ -f "$HOME/bin/mycommon" ]; then
+    . "$HOME/bin/mycommon"
+fi
+
 # help text
-function usage() {
+function usage(){
     echo "Usage:  cryptIt [options] [filename]."
     echo "Purpose: encrypt/decrypt files."
     echo "       "
@@ -14,16 +18,14 @@ function usage() {
     echo "cryptIt -e  README.txt"
     echo "cryptIt -d  "
     echo "cryptIt -d  README.txt.asc"
-    echo "       "
 }
 
 # Select a file using zenity/yad dialog
-function selcryptfile () {
-    local has_yad=`which yad`
-    if [ -z "$has_yad" ]; then
-        local f=`zenity --title="zcrypt: Select a file to $1" --file-selection`
+function X_selfile(){
+    if [ -z "$(command -v yad)" ]; then
+        local f=$(zenity --title="zcrypt: Select a file to $1" --file-selection)
     else
-        local f=`yad --title="zcrypt: Select a file to $1" --file-selection --center`
+        local f=$(yad --title="zcrypt: Select a file to $1" --file-selection --center)
     fi
     
     [ $? -gt 0 ] && f="";
@@ -32,40 +34,38 @@ function selcryptfile () {
 }
 
 # Encrypt selected file
-function encryptselfile () {
-    local f=`selcryptfile "encrypt"`
+function X_encrypt(){
+    local f="$(X_selfile "encrypt")"
     if [ -z "$f" ]; then
-        zenity --error --title "File Selection" --text "You must select a file to encrypt !"
+        gxmessage --center --ontop --sticky --nofocus --title "File Selection" "You must select a file to encrypt !"
     else
         encryptit "${f}"
-        
         if [ $? -gt 0  ]; then
-            zenity --error --title "File Encrypted" --text "$f has NOT been encrypted"
+            gxmessage --center --ontop --sticky --nofocus --title "File Encrypted" "$f has NOT been encrypted"
         else
-            zenity --info --title "File Encrypted" --text "$f has been encrypted"
+            gxmessage --center --ontop --sticky --nofocus --title "File Encrypted" "$f has been encrypted"
         fi
     fi
 }
 
 # Decrypt selected file
 # NOTE: This will OVERWRITE existing files with the same name !!!
-function decryptselfile () {
-    local f=`selcryptfile "decrypt"`
+function X_decrypt(){
+    local f="$(X_selfile "decrypt")"
     if [ -z "$f" ]; then
-        zenity --error --title "File Selection" --text "You must select a file to encrypt !"
+        gxmessage --center --ontop --sticky --nofocus --title "File Selection" "You must select a file to decrypt !"
     else
         decryptit "${f}"
-        
         if [ $? -gt 0  ]; then
-            zenity --error --title "File Decrypted" --text "$f has NOT been decrypted"
+            gxmessage --center --ontop --sticky --nofocus --title "File Decrypted" "$f has NOT been decrypted"
         else
-            zenity --info --title "File Decrypted" --text "$f has been decrypted"
+            gxmessage --center --ontop --sticky --nofocus --title "File Decrypted" "$f has been decrypted"
         fi
     fi
 }
 
 # Encrypt file using ascii armor and symmetric cipher
-function encryptit () {
+function encryptit(){
     if [ -z "$1" ] || [ ! -f "$1" ]; then
         return 1
     fi
@@ -73,7 +73,6 @@ function encryptit () {
     if [ -z "$2" ] ; then
         gpg -acq --yes "${1}"
         [ $? -gt 0  ] && return 1;
-
     else
         echo "$2" | gpg -acq --batch --yes --passphrase-fd 0 "${1}"
     fi
@@ -82,7 +81,7 @@ function encryptit () {
 
 # Decrypt a file
 # NOTE: This will OVERWRITE existing files with the same name !!!
-function decryptit () {
+function decryptit(){
     if [ -z "$1" ] || [ ! -f "$1" ]; then
         return 1
     fi
@@ -120,9 +119,9 @@ function read_pf() {
 # Encryption helper
 function do_encr() {
     if [ -z "$1" ]; then
-        encryptselfile
+        X_encrypt
     else
-        [ -f "$1" ] || { echo "$1 not found. You must select a file to encrypt !"; return 1; }
+        [ ! -f "$1" ] && echo "$1 not found. You must select a file to encrypt !" && return 1
         local pf=""
         printf "Passphrase: "
         while [ -z "$pf" ]; do
@@ -144,9 +143,9 @@ function do_encr() {
 # Decryption helper
 function do_decr() {
     if [ -z "$1" ]; then
-        decryptselfile
+        X_decrypt
     else
-        [ -f "$1" ] || { echo "$1 not found. You must select a file to decrypt !"; return 1; }
+        [ ! -f "$1" ] && echo "$1 not found. You must select a file to decrypt !" && return 1
         local pf=""
         printf "Passphrase: "
         while [ -z "$pf" ]; do
@@ -166,44 +165,53 @@ function do_decr() {
 }
 
 # Main
-if [ $# -eq 0 ] ; then
-    usage ;
-    exit 0
-fi
+function main(){
+    if [ $# -eq 0 ] ; then
+        usage ;
+        exit 1
+    fi
+    
+    # Option strings
+    local SHORT=":d::e::h"
+    local LONG=":decrypt,encrypt,help"
+    
+    # read the options
+    local OPTS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
+    if [ $? -ne 0 ] ; then
+        echo "Wrong parameters $*"
+        usage
+        exit 1
+    fi
+    
+    #eval set -- "$OPTS"
+    
+    if [ $? -ne 0 ] ; then
+        usage ;
+        exit 1
+    fi
+    
+    local fname=""
+    
+    while true ; do
+        case "$1" in
+            -d | --decrypt )
+                [ $# -gt 1 ] && fname="$2" ; shift 2
+                do_decr "$fname"
+                [ $? -gt 0  ] && exit 1 || exit 0
+            ;;
+            -e | --encrypt )
+                [ $# -gt 1 ] && fname="$2" ; shift 2
+                do_encr "$fname"
+                [ $? -gt 0  ] && exit 1 || exit 0
+            ;;
+            -h | --help )
+                usage && exit 0
+            ;;
+            *)  usage && exit 1
+            ;;
+        esac
+    done
+}
 
-# Option strings
-SHORT=":d::e::h"
-LONG=":decrypt,encrypt,help"
+main "$@"
 
-# read the options
-OPTS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
-if [ $? -ne 0 ] ; then
-    echo "Wrong parameters $*";
-    usage ;
-    exit 1
-fi
-
-#eval set -- "$OPTS"
-
-if [ $? -ne 0 ] ; then
-    usage ;
-    exit 1
-fi
-
-fname=""
-
-while true ; do
-    case "$1" in
-        -d | --decrypt )
-            [ $# -gt 1 ] && fname="$2" ; shift 2
-            do_decr "$fname"
-            [ $? -gt 0  ] && exit 1 || exit 0
-        ;;
-        -e | --encrypt )
-            [ $# -gt 1 ] && fname="$2" ; shift 2
-            do_encr "$fname"
-            [ $? -gt 0  ] && exit 1 || exit 0
-        ;;
-        *)  usage; exit;;
-    esac
-done
diff --git a/bin/mycommon b/bin/mycommon
--- a/bin/mycommon
+++ b/bin/mycommon
@@ -4,15 +4,10 @@ test -f ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs && source ${XDG_CONFIG_HOME
 
 # Find and/or create path for logging
 function doLogPath() {
-    local fpPath="/var/log"
-    [ ! -w "$fpPath" ] && fpPath="$HOME/.local/var/log" ;
-    [ ! -d "$fpPath" ] && mkdir -p $fpPath ;
-    if [ ! -d "$fpPath" ]; then
-        echo ""
-        return 1
-    fi
-    echo "$fpPath"
-    return 0
+    local lpath="/var/log"
+    [ -w "$lpath" ] && echo "$lpath" && return 0  || lpath="$HOME/.local/var/log"
+    [ ! -d "$lpath" ] && mkdir -p $lpath 
+    [ -d "$lpath" ] && echo "$lpath" && return 0 || echo "" &&  return 1
 }
 
 # Script name that is sourcing this
@@ -42,12 +37,18 @@ function log() {
 
 function bailout () {
     echo "Error: $@"
+    [ -f "$myLogFile" ] && log "Error: $@"
     exit 1
 }
 
-# Check required software
+# Check for required software
 function precheck () {
     hash "$1" >/dev/null 2>&1 || bailout "Please install $1"
+}
+
+# Check for software existence 
+function checkfor () {
+    hash "$1" >/dev/null 2>&1 && return 0 || return 1
 }
 
 # direct it all to /dev/null
@@ -65,12 +66,46 @@ function is_git_repository() {
     [ "$(git rev-parse &>/dev/null; printf $?)" -eq 0 ] && return 0 || return 1
 }
 
-# Trim leading and tailing spaces
+# Trim all spaces
 # Usage: trim_string "   example   string    "
-function trim_string() {
+function trim_spaces() {
     : "${1#"${1%%[![:space:]]*}"}"
     : "${_%"${_##*[![:space:]]}"}"
     printf '%s\n' "$_"
+}
+
+# remove trailing slash (substitute for realpath -s)
+# warning: returns empty if $1 is just /
+function trim_slash() {
+    printf "%s" "${1%/}"
+}
+
+# Trim leading spaces
+# Usage: ltrim "   example   string    "
+function ltrim() {
+    : "${1#"${1%%[![:space:]]*}"}"
+    printf '%s\n' "$_"
+}
+
+# Trim tailing spaces
+# Usage: rtrim "  example   string    "
+function rtrim() {
+    : "${1%"${1##*[![:space:]]}"}"
+    printf '%s\n' "$_"
+}
+
+# Ask for a simple yes/no confirmation
+# Usage: ask_confirmation "Are you ready?"
+function ask_confirmation() {
+    printf "\n${_cl_bold}$@${_cl_reset}"
+    read -p " (y/n) " -n 1
+    printf "\n"
+}
+
+# Test whether the result of an 'ask' is a confirmation
+# Usage: is_confirmed 
+function is_confirmed() {
+    [[ "$REPLY" =~ ^[Yy]$ ]] && return 0 || return 1
 }
 
 # Usage: say text [delayAfterText]
@@ -79,58 +114,71 @@ function say() {
     snore "${2-0}"
 }
 
-# Adapted from Addy
-# 'battery_stt -i' = with icon, 'battery' = text only
-function battery_stt(){
-    local BATTERY=0
-    local BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
-    local BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
-    local BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
-    
-    if [[ "${BATTERY_STATE}" = "Charging" ]]; then
-        if  [[ $1 = "-i" ]]; then
-            echo "  ${BATTERY_POWER}%+"
-        else
-            echo "${BATTERY_POWER}%+"
-        fi
-    elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
-        if  [[ $1 = "-i" ]]; then
-            echo "  ${BATTERY_POWER}%-"
-        else
-            echo "${BATTERY_POWER}%-"
-        fi
-    else
-        if  [[ $1 = "-i" ]]; then
-            echo "  ${BATTERY_POWER}%"
-        else
-            echo "${BATTERY_POWER}%"
-        fi
-    fi
-}
-
 # ps with ISO date format
 function ps_ISO(){
     if [ -z "$1" ]; then
-        ps -eo etimes,ruser,pid,cmd --sort=start_time | \
-            awk 'BEGIN{now=systime()} {$1=strftime("%Y-%m-%d-%H:%M:%S", now-$1); print $0}' | grep -v "grep" | grep -v "awk"
+        ps -eo etimes,ruser,pid,ppid,cmd --sort=start_time | awk 'BEGIN{now=systime()} {$1=strftime("%Y-%m-%d-%H:%M:%S", now-$1); print $0}' | grep -v "grep" | grep -v "awk"
     else
-        ps -eo etimes,ruser,pid,cmd --sort=start_time | \
-            awk 'BEGIN{now=systime()} {$1=strftime("%Y-%m-%d-%H:%M:%S", now-$1); print $0}' | grep -v "grep" | grep -v "awk" | grep "$1"
+        ps -eo etimes,ruser,pid,ppid,cmd --sort=start_time | awk 'BEGIN{now=systime()} {$1=strftime("%Y-%m-%d-%H:%M:%S", now-$1); print $0}' | grep -v "grep" | grep -v "awk" | grep "$1"
     fi
 }
 
-# Kill older instances of itself
+# Kill older instances of itself (bash based scripts)
 function kill_older(){
     local s_name="${0##*/}"
     local my_pid=$$
     snore 0.3
     for i in $(ps_ISO "$s_name" | grep "$USER" | grep -P "bash" | grep -v "grep" | awk '{print $3}'); do 
         if [ "$i" != "$my_pid" ]; then
-            log "Older instances found: pid=$i  name=$s_name "
-            kill "$i" &>/dev/null || true
+            kill "$i" &>/dev/null && log "Older instances found: pid=$i  name=$s_name"
+            [ $? -ne 0 ] && kill -9 "$i" &>/dev/null && log "Older instances found: pid=$i name=$s_name" || true
         fi
     done
     return 0
+}
+
+# Kill all process by pattern (but not me)
+function kill_it(){
+    local s_name="$1"
+    snore 0.3
+    for i in $(ps_ISO "$s_name" | grep "$USER" | grep -v "grep" | awk '{print $3}'); do 
+        if [ "$i" != "$$" ]; then
+            kill "$i" &>/dev/null && log "Stopping instance(kill): pid=$i name=$s_name"
+            [ $? -ne 0 ] && kill -9 "$i" &>/dev/null && log "Stopping instance(kill): pid=$i name=$s_name" || true
+            snore 0.1
+        fi
+    done
+    return 0
+}
+
+# Cleanup running processes.
+function stop_it() {
+    [ -z "$1" ] && return 1
+    local s_name="$1"
+    case ${2:-stop} in
+        stop)
+            for i in $(ps_ISO "$s_name" | grep -v "grep" | awk '{print $3}'); do 
+                kill "$i" &>/dev/null && log "Stopping instance(kill): pid=$i name=$s_name"
+                [ $? -ne 0 ] && kill -9 "$i" &>/dev/null && log "Stopping instance(kill): pid=$i name=$s_name"
+                [ $? -ne 0 ] && pkill -USR1 --euid "$(id -u)" --exact "$s_name" && log "Stopping instances(pkill): name=$s_name " 
+                [ $? -ne 0 ] && killall "$1" > /dev/null && log "Stopping instances(killall): name=$s_name " || true
+                snore 0.1
+            done
+            return 0
+        ;;
+        debug)
+            if [ $(pgrep -lfc "$1") -ge 1 ] ; then
+                log "$1 need to be terminated"
+            else
+                log "$1 not found"
+            fi
+            return 0
+        ;;
+        *)
+            log "2nd argument must be: stop or debug";
+            return 1
+        ;;
+    esac
 }
 
 # Return 0 if user in the active session can issue power related commands via policykit
@@ -139,21 +187,25 @@ function auth_user() {
     return 1
 }
 
+# Check if can hibernate using dbus
 function can_hibernate() {
     [ $(qdbus --system org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.CanHibernate | grep "yes") ] && return 0
     return 1
 }
 
+# Check if can poweroff using dbus
 function can_poweroff() {
     [ $(qdbus --system org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.CanPowerOff | grep "yes") ] && return 0
     return 1
 }
 
+# Check if can reboot using dbus
 function can_reboot() {
     [ $(qdbus --system org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.CanReboot | grep "yes") ] && return 0
     return 1
 }
 
+# Check if can suspend using dbus
 function can_suspend() {
     [ $(qdbus --system org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.CanSuspend | grep "yes") ] && return 0
     return 1
@@ -191,44 +243,9 @@ function dbus_suspend() {
     /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true
 }
 
-# Return 0 if systemctl is found.
-function systemctl_ok() {
-    [ $(command -v systemctl) ] && return 0
-    return 1
-}
-
-# Return 0 if shutdown is found.
-function shutdown_ok() {
-    [ $(command -v shutdown) ] && return 0
-    return 1
-}
-
-# Return 0 if init is found.
-function init_ok() {
-    [ $(command -v init) ] && return 0
-    return 1
-}
-
-# Is the screen already locked?
-function locked() {
-    local DebugMode=${1:-no}
-    local scrsvApps=('i3lock' 'mate-screensaver-dialog' 'cinnamon-screensaver-pam-helper' 'slimlock' 'gnome-screensaver-dialog' 'xscreensaver')
-    local c=0
-    for p1 in "${scrsvApps[@]}"; do
-        c=$(pgrep -lfc "${p1}")
-        if [ $c -gt 0 ] ; then
-            if [ "$DebugMode" = "debug" ]; then
-                log "${p1} found and active";
-                return 0;
-            fi
-        fi
-    done
-    return 1;
-}
-
 # Control the dunst daemon, if it is running.
 function dunstctl() {
-    pkill -0 --exact dunst || return 0
+    [ $(pgrep -lfc dunst) -ge 1 ] || return 0
     
     case ${1:-} in
         stop)
@@ -238,10 +255,12 @@ function dunstctl() {
         resume)
             log "...Resuming notifications."
             pkill -USR2 --euid "$(id -u)" --exact dunst
+            dunst &
+            disown
         ;;
         check)
             log "Checking for dunst."
-            [ $(command -v dunst) ] && return 0 || return 1
+            checkfor "dunst" && return 0 || return 1
         ;;
         *)
             echo "dunstctl argument required: stop, resume or check"
@@ -251,196 +270,129 @@ function dunstctl() {
     return 0
 }
 
-# Cleanup running processes.
-function stop_it() {
-    [ -z "$1" ] && return 1
-    
-    case ${2:-} in
-        stop)
-            if [ $(pgrep -lfc "$1") -ge 1 ] ; then
-                local v_pid=( $(ps -aux | grep "$1" | egrep -v 'grep --color=auto' | sort -u | awk '{print $2}') )
-                local v_len=${#v_pid[@]}
-                let v_len=v_len-1
-                local one_pid="0"
-                for i in $(seq 0 $v_len ); do
-                    one_pid=$(echo "${v_pid[$i]}");
-                    log "killing $1 pid= $one_pid"
-                    kill "$one_pid" &>/dev/null || true
-                    sleep 0.1;
-                done
-            fi
-            return 0
-        ;;
-        debug)
-            if [ $(pgrep -lfc "$1") -ge 1 ] ; then
-                log "$1 need to be terminated"
-            else
-                log "$1 not found"
-            fi
-            return 0
-        ;;
-        *)
-            log "2nd argument must be: stop or debug";
-            return 1
-        ;;
-    esac
-}
-
 # xset required
 # check for a running X server
 function is_running_X(){
-    if ! xset q &>/dev/null; then
-        return 1
-    fi
-    return 0
+    xset q &>/dev/null && return 0 || return 1
 }
 
-# builtin sleep in bash
+# Is the screen already locked?
+function locked() {
+    local sclist=('i3lock' 'mate-screensaver-dialog' 'cinnamon-screensaver-pam-helper' 'slimlock' 'gnome-screensaver-dialog' 'xscreensaver')
+    for p in "${sclist[@]}"; do
+        [ $(pgrep -lfc "${p}") -gt 0 ] && return 0;
+    done
+    return 1;
+}
+
+# builtin sleep version in bash
 function snore(){
     local IFS
     [[ -n "${_snore_fd:-}" ]] || exec {_snore_fd}<> <(:)
     read ${1:+-t "$1"} -u $_snore_fd || :
 }
 
-# required awk, bc
+# helper find normal icon fullname file path
+function findNrmIconHelper(){
+    [ -z "$1" ] && echo "" && return 1
+    [ -z "$2" ] && echo "" && return 1
+    cd "${1}"
+    find . -name "${2}" | grep "svg\|png\|jpg" | cut -c 2- | head -n 1
+    return 0
+}
+
+# helper find status icon fullname file path
+function findStatIconHelper(){
+    [ -z "$1" ] && echo "" && return 1
+    [ -z "$2" ] && echo "" && return 1
+    cd "${1}"
+    find . -name "${2}" | grep "svg\|png\|jpg" | grep -i "status" | cut -c 2- | tail -n 1
+    return 0
+}
+
+# find jpg icon fullname file path
 function findJPGPath(){
-    if [ -z "$1" ] || [ -z "$2" ]; then
-        echo ""
-        return 1
-    fi
-    local iconJPG="${2}.jpg"
-    cd "${1}"
-    find . -name "${iconJPG}" | grep "16" | cut -c 2- | tail -n 1
+    findNrmIconHelper "$1" "${2}.jpg" | grep "16"
     return 0
 }
 
+# find png icon fullname file path
 function findPNGPath(){
-    if [ -z "$1" ] || [ -z "$2" ]; then
-        echo ""
-        return 1
-    fi
-    local iconPNG="${2}.png"
-    cd "${1}"
-    find . -name "${iconPNG}" | grep "16" | cut -c 2- | tail -n 1
+    findNrmIconHelper "$1" "${2}.png" | grep "16"
     return 0
 }
 
+# find svg icon fullname file path
 function findSVGPath(){
-    if [ -z "$1" ] || [ -z "$2" ]; then
-        echo ""
-        return 1
-    fi
-    local iconSVG="${2}.svg"
-    cd "${1}"
-    find . -name "${iconSVG}" | cut -c 2- | tail -n 1
+    findNrmIconHelper "$1" "${2}.svg"
     return 0
 }
 
+# find current icon theme name
 function findIconThemeName(){
     local tn=""
-    tn=$(gsettings get org.mate.interface icon-theme | tr -d "'")
-    [ -z "$tn" ] && tn=$(gsettings get org.gnome.desktop.interface icon-theme | tr -d "'")
+    hash dump_xsettings && tn="$(dump_xsettings | grep "Net\/IconThemeName" | awk '{print $2}' | tr -d '"')"
+    [ -z "$tn" ] && tn="$(gsettings get org.mate.interface icon-theme | tr -d "'")"
+    [ -z "$tn" ] && tn="$(gsettings get org.gnome.desktop.interface icon-theme | tr -d "'")"
     echo "$tn"
     return 0
 }
 
+# find current icon theme path for search
 function findIconThemePath(){
-    if [ -z "$1" ]; then
-        echo ""
-        return 1
-    fi
+    [ -z "$1" ] && echo "" && return 1
     local tn="$1"
-    local tp=""
-    tp="/usr/share/icons/$tn"
-    
-    if [ -d "$tp" ]; then
-        echo "$tp"
-        return 0
-    else
-        tp="$HOME/.icons/$tn"
-        if [ -d "$tp" ]; then
-            echo "$tp"
-            return 0
-        fi
-    fi
+    local tp="/usr/share/icons/$tn"
+    [ -d "$tp" ] && echo "$tp" && return 0
+    tp="$HOME/.icons/$tn"
+    [ -d "$tp" ] && echo "$tp" && return 0
     echo ""
     return 1
 }
 
+# find icon path inside current icon theme
 function FindIconPath(){
     if [ -z "$1" ] || [ -z "$2" ]; then
         echo ""
         return 1
     fi
-    
     local tp="$2"
-    local nip=""
-    
-    nip=$(findSVGPath "$tp" "${1}")
-    [ -z "$nip" ] && nip=$(findPNGPath "$tp" "${1}")
-    [ -z "$nip" ] && nip=$(findJPGPath "$tp" "${1}")
-    if [ -z "$nip" ]; then
-        echo ""
-        return 1
-    fi
-    
+    local nip=$(findNrmIconHelper "$tp" "${1}.svg" )
+    [ -z "$nip" ] && nip=$(findNrmIconHelper "$tp" "${1}.png" | grep "16")
+    [ -z "$nip" ] && nip=$(findNrmIconHelper "$tp" "${1}.jpg" | grep "16")
+    [ -z "$nip" ] && echo "" && return 1
     echo "$tp$nip"
     return 0
 }
 
+# find icon path on fallback conditions
 function FallbackiconPath(){
     if [ -z "$1" ] || [ -z "$2" ]; then
         echo ""
         return 1
     fi
     
-    local tp="$2"
-    local seaDirs=( $(grep "nherit" "$tp/index.theme" | cut -d"=" -f2 | xargs -d ",") )
+    local sdirs=( $(grep "nherit" "$2/index.theme" | cut -d"=" -f2 | xargs -d ",") )
     local tp=""
-    local iconPath=""
+    local nip=""
     
-    for i in "${seaDirs[@]}"; do
+    for i in "${sdirs[@]}"; do
         tp=$(findIconThemePath "$i");
-        iconPath=$(FindIconPath "$1" "$tp");
+        nip=$(FindIconPath "$1" "$tp");
         #echo "o i = $i e o tp = $tp e o iconName=$1  e o iconPath = $iconPath"
-        if [ ! -z "$iconPath" ]; then
-            echo "$iconPath"
-            return 0
-        fi
+        [ ! -z "$nip" ] && echo "$nip" && return 0
     done
     echo ""
     return 1
 }
 
+# find icon path 
 function iconPath(){
-    if [ -z "$1" ]; then
-        echo ""
-        return 1
-    fi
-    
-    local themePath=""
-    local iconPath=""
-    local themeName=""
-    
-    themeName=$(findIconThemeName)
-    themePath=$(findIconThemePath "$themeName")
-    
-    if [ -z "$themePath" ]; then
-        echo ""
-        return 1
-    fi
-    
-    iconPath=$(FindIconPath "$1" "$themePath");
-    
-    if [ -z "$iconPath" ]; then
-        iconPath=$(FallbackiconPath "$1" "$themePath")
-        if [ -z "$iconPath" ]; then
-            echo ""
-            return 1
-        fi
-    fi
-    
+    [ -z "$1" ] && echo "" && return 1
+    local themePath="$(findIconThemePath "$(findIconThemeName)")"
+    [ -z "$themePath" ] && echo "" && return 1
+    local iconPath="$(FindIconPath "$1" "$themePath")"
+    [ -z "$iconPath" ] && iconPath=$(FallbackiconPath "$1" "$themePath")
     echo "$iconPath"
     return 0
 }
-
diff --git a/bin/touchpadctl b/bin/touchpadctl
--- a/bin/touchpadctl
+++ b/bin/touchpadctl
@@ -1,97 +1,108 @@
 #!/usr/bin/env bash
 ## $1 = "add" / "remove"
 ## $2 = %k from udev
+set -eu
 
 function usage() {
-    echo "Usage: $0 [Options]"
+    echo "Usage: $(basename $0) [Options]"
     echo "       "
-    echo "Purpose: enable|disable Touchpad"
+    echo "Purpose: To enable or disable Touchpad"
     echo "       "
     echo "Options"
-    echo "-h: Show this help"
-    echo "-d: Disable touchpad"
-    echo "-e: Enable touchpad"
-    echo "-a: Auto enable|disable on mouse plug(in/off)"
-    echo "--disable: Disable touchpad"
-    echo "--enable: Enable touchpad"
+    echo "-h | --help : Show this help"
+    echo "-d | --disable: Disable touchpad"
+    echo "-e | --enable: Enable touchpad"
     return 0;
 }
 
-# Main
-if [ $# -eq 0 ] ; then
-    usage ;
-    /usr/bin/logger -t Touchpadctl -- "No parameters."
-    exit 0
-fi
+function touch_hnd_noX(){
+    case "$1" in
+        -d | --disable)
+            echo -n manual > $base_dir/bind_mode && /usr/bin/logger -t Touchpadctl -- "Disabling the touchpad" || /usr/bin/logger -t Touchpadctl -- "Cannot disable touchpad"
+            echo -n $device_id > $base_dir/unbind 2>/dev/null || true
+        ;;
+        -e | --enable)
+            echo -n auto > $base_dir/bind_mode && /usr/bin/logger -t Touchpadctl -- "Enabling the touchpad" || /usr/bin/logger -t Touchpadctl -- "Cannot enable touchpad"
+        ;;
+        *)  usage
+            exit 0
+        ;;
+    esac
+}
 
-# Option strings
-SHORT=":a::d::e::h"
-LONG=":auto,disable,enable,help"
-
-# Read the options
-OPTS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
-if [ $? -ne 0 ] ; then
-    usage ;
-    /usr/bin/logger -t Touchpadctl -- "Wrong parameters.[ $* ]"
-    exit 0
-fi
-
-# Obtain user list
-USERLIST=$(w -h | cut -d' ' -f1 | sort | uniq)
-for CUR_USER in ${USERLIST}; do
-    CUR_USER_XAUTH="$(sudo -Hiu "${CUR_USER}" env | grep -e "^HOME=" | cut -d'=' -f2)/.Xauthority"
-    ## Can't find a way to get another users DISPLAY variable from an isolated root environment. Have to set it manually.
-    CUR_USER_DISPL="$(sudo -Hiu "${CUR_USER}" env | grep -e "^DISPLAY=" | cut -d'=' -f2)"
-    [ -z "$CUR_USER_DISPL" ] && CUR_USER_DISPL=":0"
+function touch_hnd_X(){
+    local usr="$2"
+    local touch_id=$(/usr/bin/xinput list | \egrep -Eo 'Touchpad\s*id\=[0-9]{1,2}' | \egrep -Eo '[0-9]{1,2}')
+    local touch_stt=$(/usr/bin/xinput list-props $touch_id | \grep 'Device Enabled' | \awk '{print $4}')
+    [ $touch_id -eq 0 ] && /usr/bin/logger -t Touchpadctl -- "Touchpad device not found. $usr. ($XAUTHORITY - $DISPLAY)"
     
-    export XAUTHORITY="${CUR_USER_XAUTH}"
-    export DISPLAY="${CUR_USER_DISPL}"
-    
-    # Check running X
-    if ! xset q &>/dev/null; then
-        /usr/bin/logger -t Touchpadctl -- "Xserver is not running."
-        exit 0
+    case "$1" in
+        -a | --auto )
+            local mouse_id="$(xinput list | \egrep -Eo '[Mm]ouse\s*id\=[0-9]{1,2}' | \egrep -Eo '[0-9]{1,2}')"
+            local mouse_stt=$(/usr/bin/xinput list-props $mouse_id | \grep 'Device Enabled' | \awk '{print $4}')
+            if [ $mouse_id -ne 0 ] && [ $mouse_stt -eq 1 ]; then
+                /usr/bin/xinput disable $touch_id
+                /usr/bin/logger -t Touchpadctl -- "Additional external mice found. Touchpad disabled for $usr. ($XAUTHORITY - $DISPLAY)"
+            else
+                /usr/bin/xinput enable $touch_id
+                /usr/bin/logger -t Touchpadctl -- "Additional external mice not found. Touchpad enabled for $usr. ($XAUTHORITY - $DISPLAY)"
+            fi
+        ;;
+        -d | --disable )
+            if [ $touch_stt -eq 1 ]; then
+                /usr/bin/xinput disable $touch_id
+                /usr/bin/logger -t Touchpadctl -- "Disabling touchpad for $usr. ($XAUTHORITY - $DISPLAY)"
+            else
+                /usr/bin/logger -t Touchpadctl -- "Touchpad already disabled for $usr. ($XAUTHORITY - $DISPLAY)"
+            fi
+        ;;
+        -e | --enable )
+            if [ $touch_stt -eq 0 ]; then
+                /usr/bin/xinput enable $touch_id
+                /usr/bin/logger -t Touchpadctl -- "Enabling touchpad for $usr. ($XAUTHORITY - $DISPLAY)"
+            else
+                /usr/bin/logger -t Touchpadctl -- "Touchpad already enabled for $usr. ($XAUTHORITY - $DISPLAY)"
+            fi
+        ;;
+        *)  usage
+            exit 0
+        ;;
+    esac
+}
+
+user_list="$(w -h | cut -d' ' -f1 | sort | uniq)"
+user_id="$(id -u)"
+base_dir=/sys/bus/serio/drivers/psmouse
+device_id=serio1
+
+function main(){
+    if [ $# -eq 0 ]; then
+        usage
+        exit 1
     fi
     
-    if [ -f "${CUR_USER_XAUTH}" ]; then
-        declare -i ID
-        ID=$(/usr/bin/xinput list | \egrep -Eo 'Touchpad\s*id\=[0-9]{1,2}' | \egrep -Eo '[0-9]{1,2}')''
-        declare -i STATE
-        STATE=$(/usr/bin/xinput list-props $ID | \grep 'Device Enabled' | \awk '{print $4}')
-        
-        case "$1" in
-            -a | --auto )
-                xinput list | \egrep -Eo '[Mm]ouse\s*id\=[0-9]{1,2}' | \egrep -Eo '[0-9]{1,2}' &>/dev/null
-                if [ $? -eq 0 ] ; then
-                    /usr/bin/xinput disable $ID
-                    /usr/bin/logger -t Touchpadctl -- "Additional external mice found. Touchpad disabled for $CUR_USER. ($XAUTHORITY - $DISPLAY)"
-                else
-                    /usr/bin/xinput enable $ID
-                    /usr/bin/logger -t Touchpadctl -- "Additional external mice not found. Touchpad enabled for $CUR_USER. ($XAUTHORITY - $DISPLAY)"
-                fi
-            ;;
-            -d | --disable )
-                if [ $STATE -eq 1 ]; then
-                    /usr/bin/xinput disable $ID
-                    /usr/bin/logger -t Touchpadctl -- "Disabling touchpad for $CUR_USER. ($XAUTHORITY - $DISPLAY)"
-                else
-                    /usr/bin/logger -t Touchpadctl -- "Touchpad already disabled for $CUR_USER. ($XAUTHORITY - $DISPLAY)"
-                fi
-            ;;
-            -e | --enable )
-                xinput list | \egrep -Eo '[Mm]ouse\s*id\=[0-9]{1,2}' | \egrep -Eo '[0-9]{1,2}' &>/dev/null
-                if [ $? -eq 0 ] ; then
-                    /usr/bin/logger -t Touchpadctl -- "Additional external mice found. Touchpad not enabled for $CUR_USER. ($XAUTHORITY - $DISPLAY)"
-                    exit 0
-                fi
-                if [ $STATE -eq 0 ]; then
-                    /usr/bin/xinput enable $ID
-                    /usr/bin/logger -t Touchpadctl -- "No additional external mice found. Enabling touchpad for $CUR_USER. ($XAUTHORITY - $DISPLAY)"
-                else
-                    /usr/bin/logger -t Touchpadctl -- "Touchpad already enabled for $CUR_USER. ($XAUTHORITY - $DISPLAY)"
-                fi
-            ;;
-            *)  usage; exit;;
-        esac
-    fi
-done
+    for u in ${user_list}; do
+        ## Can't find a way to get another users DISPLAY variable from an isolated root environment. Have to set it manually.
+        displ="$(sudo -Hiu "${u}" env | grep -e "^DISPLAY=" | cut -d'=' -f2)"
+        [ -z "$displ" ] && displ=":0"
+        export XAUTHORITY="$(sudo -Hiu "${u}" env | grep -e "^HOME=" | cut -d'=' -f2)/.Xauthority"
+        export DISPLAY="${displ}"
+        if [ -f "${XAUTHORITY}" ]; then
+            # Check running X
+            if ! xset q &>/dev/null; then
+                /usr/bin/logger -t Touchpadctl -- "Xserver is not running."
+                touch_hnd_noX "$1" "$u"
+            else
+                /usr/bin/logger -t Touchpadctl -- "Xserver is running."
+                touch_hnd_X "$1" "$u"
+            fi
+        fi
+    done
+}
+
+main "$@"
+
+unset user_list
+unset user_id
+unset base_dir
+unset device_id
