Apr 2025 upd

diff --git a/bin/mycommon b/bin/mycommon
--- a/bin/mycommon
+++ b/bin/mycommon
@@ -569,7 +569,41 @@ function snore(){
     [ -z "$1" ] && return 0
     local IFS
     [[ -n "${_snore_fd:-}" ]] || exec {_snore_fd}<> <(:)
+    #[[ -n "${_snore_fd:-}" ]] || { exec {_snore_fd}<> <(:); } 2>/dev/null ||
+    #{
+    #    # workaround for MacOS and similar systems
+    #    local fifo
+    #    fifo=$(mktemp -u)
+    #    mkfifo -m 700 "$fifo"
+    #    exec {_snore_fd}<>"$fifo"
+    #    rm "$fifo"
+    #}
     read ${1:+-t "$1"} -u $_snore_fd || :
+}
+
+# Diff between dates in seconds
+function dateDiffS() {
+    local d1=$(date -d "$1" +%s)
+    local d2=$(date -d "$2" +%s)
+    echo $(( (((d1-d2) > 0 ? (d1-d2) : (d2-d1))) ))
+}
+
+# Diff between dates in days
+function dateDiffD() {
+    local d1=$(date -d "$1" +%s)
+    local d2=$(date -d "$2" +%s)
+    echo $(( (((d1-d2) > 0 ? (d1-d2) : (d2-d1)) + 43200) / 86400 ))
+}
+
+# Snores until a date/time has come
+function snoreUntil {
+    local seconds=0
+    # Use $* to eliminate need for quotes
+    seconds=$(( $(date -d "$*" +%s) - $(date +%s) ))
+    [ $? -ne 0 ] && echo "Invalid date/time specification" && return 1
+    [ $seconds -le 0 ] && echo "Date/time must be greater than current date/time" && return 1
+    echo "Sleeping for $seconds seconds"
+    snore $seconds
 }
 
 # helper find normal icon fullname file path
diff --git a/bin/ob_end_session b/bin/ob_end_session
--- a/bin/ob_end_session
+++ b/bin/ob_end_session
@@ -5,30 +5,39 @@ if [ -f "$HOME/bin/mycommon" ]; then
     . "$HOME/bin/mycommon"
 fi
 
-dunstctl stop
+# Proper Killing processes using kill command
+function overkill(){
+    kill -SIGTERM "$1" > /dev/null 2>&1 || true
+    while 2>/dev/null kill -0 "$1"; do
+        for SIG in 2 9 ; do 
+            if ps -p $1 > /dev/null; then
+                kill -$SIG "$1" > /dev/null 2>&1 || true; 
+                snore 0.3; 
+            fi
+        done
+    done
+    return 0
+    #ps -p $1 > /dev/null 2>&1 && return 1 || return 0
+}
 
-# Stop this session and daemon running processes.
-stop_it "polkit-gnome-authentication-agent-1" "stop"
-stop_it "gnome-keyring-daemon" "stop"
-stop_it "gnome-settings-daemon" "stop"
-stop_it "gnome-screensaver" "stop"
-stop_it "polkit-mate-authentication-agent-1" "stop"
-stop_it "mate-settings-daemon" "stop"
-stop_it "mate-power-manager" "stop"
-stop_it "mate-volume-control-applet" "stop"
-stop_it "mate-screensaver" "stop"
-stop_it "cinnamon-screensaver" "stop"
-stop_it "xscreensaver" "stop"
-stop_it "xautolock" "stop"
-stop_it "mylightson" "stop"
-stop_it "mywallchng" "stop"
-stop_it "tint2" "stop"
-stop_it "compton" "stop"
+function main(){
+    local OLD_IFS=$IFS
 
-openbox --exit;
+    checkfor "dunstctl" && dunstctl stop
 
-killall openbox;
+    IFS=$'\n'
+    for i in $(pgrep -lf -u $USER | grep -v "gvfs\|systemd\|(sd-pam)\|gconf\|dconf\|dbus\|openbox"); do
+        overkill $(awk '{print $1}' <<< $i)
+    done
+    IFS=$OLD_IFS
+   
+    openbox --exit;
+    
+    killall openbox || true;
+    
+    # dbus-launch cleanup
+    pkill -u $USER -t `tty | cut -d '/' -f 3,4` dbus-launch || true
+}
 
-# dbus-launch cleanup
-pkill -u $USER -t `tty | cut -d '/' -f 3,4` dbus-launch
+main "$@"
 
